name: Check all node 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  echo_github_gestristed:
    name: echo git hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
      - name: npm ci
        run: npm ci
      - name: npm run test
        run: npm run test
      - name: run  versioning
        run: npx semantic-release
